---
- hosts: all
  tasks:
    - name: install driman key
      authorized_key:
        user: root
        state: present
        key: '{{ item }}'
      with_file:
        - driman.pub
        - jk.pub

    - name: install shell packages
      apt:
        name:
          - kitty-terminfo
          - fish

    - name: change shell for users
      user:
        name: '{{ item }}'
        shell: /usr/bin/fish
      loop:
        - root
