---
- hosts: all
  gather_facts: yes
  tasks:
    - include_tasks: tasks/fontawesome.yml
  tags: [sway, waybar]

- hosts: cli:desktop
  roles:
    - role: runit
      tags: runit
      when: ansible_service_mgr == "runit"
    - role: fish
      tags: fish
    - role: neovim
      tags: neovim
    - role: screen
      tags: screen
    - role: git
      tags: git,cli
    - role: ssh
      tags: ssh 
    - role: htop
      tags: htop

- hosts: desktop
  roles:
    - role: gtk
      tags: gtk
      vars:
        theme: "Adwaita-dark"
      when: ansible_user_id != 'root'
    - role: gpg
      tags: gpg
      when: ansible_user_id != 'root'
    - role: dav
      tags: dav
      when: ansible_user_id != 'root'
    - role: sway
      tags: sway
      when: ansible_user_id != 'root'
    - role: waybar
      tags: waybar
      when: ansible_user_id != 'root'
    - role: pipewire
      tags: pipewire
      when: ansible_user_id != 'root'
    - role: wofi
      tags: wofi
      when: ansible_user_id != 'root'
    - role: mako
      tags: mako
      when: ansible_user_id != 'root'
    - role: kitty
      tags: kitty
      when: ansible_user_id != 'root'
    - role: mpv
      tags: mpv
      when: ansible_user_id != 'root'
    - role: imv
      tags: imv
      when: ansible_user_id != 'root'
